name: contract

on:
  push:
    paths:
      - '.cargo/**'
      - 'src/contract/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
    branches:
      - main
  pull_request:
    paths:
      - '.cargo/**'
      - 'src/contract/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
    branches:
      - main

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: stable
          profile: minimal
          override: true
      - run: sudo apt-get install -y binaryen wabt
      - run: cargo install wasm-snip wasm-gc
      - run: yarn contract-build
      - run: yarn contract-qa
